import type { Metadata } from "next";
import { Raleway} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/header/navbar";
import CategoriesBar from "@/components/header/categoriesbar";
import Footer from "@/components/footer";
import { Providers  } from "../state/provider"; 

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
    <html lang="en">
      <body className={raleway.className}>
          <NavBar />
      <CategoriesBar />
        {children}
        <Footer />
      </body>
      </html>
      </Providers>
  );
}
